language: ruby
rvm:
  - 2.2
  - 2.3.3
  - 2.4.0

install:
  - gem install rspec bundler yard --no-document
  - gem install rubocop -v 0.47.1 --no-document

branches:
  only:
    - master

addons:
  code_climate:
    repo_token:
      baf49ba5ed8b570cece5bc38b499567850718dfd06581c285d90fd2676a4764c

script:
  - rubocop
  - rspec
